version: '3.8'

services:
  db:
    image: postgres
    container_name: open-movie-db
    hostname: db
    networks:
      openmovienet:
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  open-movie:
    build:
      context: .
    depends_on:
      - db
    container_name: rest-server
    hostname: rest-server
    networks:
      openmovienet:
    ports:
      - 4000:4000
    environment:
      - GREENLIGHT_DB_DSN=postgres://greenlight:pa55word@db:5432/greenlight?sslmode=disable
    deploy:
      restart_policy:
        condition: on-failure
        

volumes:
  postgres:

networks:
  openmovienet:
